Revert "package/linux-tools: perf: build perf with libtraceevent support when it is selected"
This reverts commit f78b3d985cd48ace97d3a403cd6e0c6a49060544.

The reverted commit alone produces:

  util/trace-event.h:149:62: error: operator '&&' has no right operand

Based on my testing, a complete solution would be:

  - reapply the reverted commit, which is patch 1 of [0]
  - apply patch 2 of [0]
  - bump to kernel 6.6.99, which has commit "perf: build: Setup
    PKG_CONFIG_LIBDIR for cross compilation" [1]

The above steps can be done later to have uprobes in perf, but that is
currently not required for the labs. For now let's get back to a
known-working codebase.

[0] https://lore.kernel.org/buildroot/20250709-perf_libtraceevent-v2-0-3ea54fbe6b5b@bootlin.com/
[1] https://lore.kernel.org/stable/2025070955-discover-tree-644c@gregkh/T/#m394f2c9392da7cfd3ca130af6a7ec8ff6ee4b6bf

Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>